call Costco_ABC.bat
call HomeDepot_ABC.bat
call MACYS_ABC.bat
call Chewy_ABC.bat
call eBay_ABC.bat
call Sams_ABC.bat
call Target_ABC.bat
call WMT_ABC.bat
call Zinus_ABC.bat
call USWayfair_ABC.bat
call OVERSTOCK_ABC.bat